fix(linter): check whether path is under root before ignoring it (#20101)
### Bug Description

When `ignorePatterns` is set in the cwd `.oxlintrc.json` file, and we
try to lint a file outside of the cwd, we get a panic:

```
thread 'tokio-runtime-worker' (171644) panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ignore-0.4.25/src/gitignore.rs:232:9:
path is expected to be under the root
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens because of this line:


https://github.com/oxc-project/oxc/blob/4ea8f9a6e515ec33878d8f4f49af31003d054f56/crates/oxc_linter/src/config/ignore_matcher.rs#L65

We call `matched_path_or_any_parents` (which can panic if path is not
under root, see
https://docs.rs/ignore/latest/ignore/gitignore/struct.Gitignore.html#panics).

### Steps to reproduce

```
mkdir ~/test1
mkdir ~/test2
cd ~/test1 && echo '{ "ignorePatterns": ["node_modules"] }' > .oxlintrc.json
touch ~/test2/test.js
oxlint ~/test2
```

### Solution

To fix this, we check whether path is under the root config's path
before deciding whether to ignore it or not. If it isn't, we don't
ignore it, otherwise we keep current behavior. This matches `oxfmt`'s
`is_path_ignored`:


https://github.com/oxc-project/oxc/blob/fb3067ca2bafbbf7d75b058788202dc16d994f3e/apps/oxfmt/src/core/config.rs#L160-L166

Fixes #22269

---------

Co-authored-by: Cameron <cameron.clark@hey.com>
Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>